version: '3.7'

services:
  nginx:
    container_name: petado_nginx
    image: nginx:stable
    depends_on:
      - server
      - mysql
    networks:
      - internal
    volumes:
      - ./nginx/image-files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 4000:80

  mysql:
    container_name: petado_mysql
    image: mysql:8.0
    networks:
      - internal
    ports:
      - 3307:3306
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=petado
      - TZ=+5:30

  server:
    container_name: petado_server
    build:
      context: .
    depends_on:
      - mysql
    networks:
      - internal
    volumes:
      - .:/workspace

networks:
  internal:
    driver: bridge

volumes:
  mysql_data:
